application: bookmarks
version: 1
runtime: python
api_version: 1

handlers:
 - url: /style
   static_dir: style

 - url: /script
   static_dir: script

 - url: /api
   script: api.py

builtins:
- datastore_admin: on
- appstats: on